[steam]
home_paths = [".local/share/Steam/steamapps/common"]
search_entity_type = "DIRECTORY"
ignore = [
    "SteamLinuxRuntime_sniper",
    "Steamworks Shared",
    "SteamLinuxRuntime",
    "SteamLinuxRuntime_soldier",
    "Proton ",
    "Steam Controller Configs"
]

[heroic-launcher]
home_paths = ["Games/Heroic"]
search_entity_type = "DIRECTORY"
ignore = ["Prefixes"]

[ubuntu-games]
search_entity_type = "EXECUTABLE"
absolute_paths = ["/usr/games/"]
ignore = [ "server" ]