[steam]
home_paths = [".local/share/Steam/steamapps/common"]
expected_type = "DIRECTORY"
ignore = [
    "SteamLinuxRuntime_sniper",
    "Steamworks Shared",
    "SteamLinuxRuntime",
    "SteamLinuxRuntime_soldier",
    "Proton ",
    "Steam Controller Configs"
]

[heroic-launcher]
home_paths = ["Games/Heroic"]
expected_type = "DIRECTORY"
ignore = ["Prefixes"]

[linux-distro-games]
expected_type = "FILE"
absolute_paths = ["/usr/games/"]
ignore = [ "server" ]